export const textVariantsLight = {
  defaults: {},
  bodyLarge: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0.5,
  },
  bodyMedium: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 14,
    fontWeight: "400",
    letterSpacing: 0.25,
  },
  bodySmall: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 12,
    fontWeight: "400",
    letterSpacing: 0.4,
  },
  displayLarge: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 96,
    fontWeight: "300",
    letterSpacing: -1.5,
  },
  displayMedium: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 60,
    fontWeight: "300",
    letterSpacing: -0.5,
  },
  displaySmall: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 48,
    fontWeight: "400",
    letterSpacing: 0,
  },
  headlineLarge: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 40,
    fontWeight: "400",
    letterSpacing: 0.25,
  },
  headlineMedium: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 34,
    fontWeight: "400",
    letterSpacing: 0.25,
  },
  headlineSmall: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 24,
    fontWeight: "400",
    letterSpacing: 0,
  },
  labelLarge: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 14,
    fontWeight: "500",
    letterSpacing: 1.25,
  },
  labelMedium: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 11,
    fontWeight: "400",
    letterSpacing: 1.5,
  },
  labelSmall: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 10,
    fontWeight: "400",
    letterSpacing: 1.5,
  },
  titleLarge: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 20,
    fontWeight: "500",
    letterSpacing: 0.15,
  },
  titleMedium: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0.15,
  },
  titleSmall: {
    // color: "#fff8f9ff",
    // textDecorationColor: "#fff8f9ff",
    fontSize: 14,
    fontWeight: "500",
    letterSpacing: 0.1,
  },
};
